apiVersion: v1
kind: Service
metadata:
  name: live-go-portal
  namespace: musti-apps
  annotations:
    field.cattle.io/targetWorkloadIds: '["musti-apps/live-go-portal"]'
    field.cattle.io/publicEndpoints: '[{"port":30004,"protocol":"TCP","serviceName":"musti-apps:live-go-portal","allNodes":true}]'
spec:
  selector:
    app: live-go-portal  
  ports:
    - name: live-go-portal
      port: 8080
      targetPort: 8080
      nodePort: 30004  ## exposed port to your local PC/server ..
  type: NodePort

